/* tslint:disable */
/* eslint-disable */
/**
 * Onshape REST API
 * ## Welcome to the Onshape REST API Explorer  To use this API explorer, sign in to your [Onshape](https://cad.onshape.com) account in another tab, then click the **Try it out** button below (it toggles to a **Cancel** button when selected).  See the **[API Explorer Guide](https://onshape-public.github.io/docs/api-intro/explorer/)** for help navigating this API Explorer, including **[authentication](https://onshape-public.github.io/docs/api-intro/explorer/#authentication)**.  **Tip:** To ensure the current session isn\'t used when trying other authentication techniques, make sure to [remove the Onshape cookie](https://support.google.com/chrome/answer/95647#zippy=%2Cdelete-cookies-from-a-site) as per the instructions for your browser. Alternatively, you can use a private or incognito window.  ## See Also  * [Onshape API Guide](https://onshape-public.github.io/docs/): Our full suite of developer guides, to be used as an accompaniment to this API Explorer. * [Onshape Developer Portal](https://dev-portal.onshape.com/): The Onshape portal for managing your API keys, OAuth2 credentials, your Onshape applications, and your Onshape App Store entries. * [Authentication Guide](https://onshape-public.github.io/docs/auth/): Our guide to using API keys, request signatures, and OAuth2 in  your Onshape applications.
 *
 * The version of the OpenAPI document: 1.181.37085-cf05a13421a3
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
     BTMDatabaseParameter2229FromJSONTyped,
     BTMParameterAppearance627FromJSONTyped,
     BTMParameterArray2025FromJSONTyped,
     BTMParameterBlobReference1679FromJSONTyped,
     BTMParameterBoolean144FromJSONTyped,
     BTMParameterConfigured2222FromJSONTyped,
     BTMParameterDerived864FromJSONTyped,
     BTMParameterEnum145FromJSONTyped,
     BTMParameterFeatureList1749FromJSONTyped,
     BTMParameterForeignId146FromJSONTyped,
     BTMParameterInvalid1664FromJSONTyped,
     BTMParameterLookupTablePath1419FromJSONTyped,
     BTMParameterMaterial1388FromJSONTyped,
     BTMParameterMultiEnum3411FromJSONTyped,
     BTMParameterQuantity147FromJSONTyped,
     BTMParameterQueryList148FromJSONTyped,
     BTMParameterQueryWithOccurrenceList67FromJSONTyped,
     BTMParameterReference2434FromJSONTyped,
     BTMParameterString149FromJSONTyped,
     BTMReadOnlyParameter3800FromJSONTyped
} from './';

/**
 * A list of parameter values for instantiation of the feature spec. Parameters are present for all defined parameters, even if not used in a specific instantiation.
 * @export
 * @interface BTMParameter1
 */
export interface BTMParameter1 {
    /**
     * Type of JSON object.
     * @type {string}
     * @memberof BTMParameter1
     */
    btType?: string;
    /**
     * Microversion that resulted from the import.
     * @type {string}
     * @memberof BTMParameter1
     */
    importMicroversion?: string;
    /**
     * ID of the parameter's node.
     * @type {string}
     * @memberof BTMParameter1
     */
    nodeId?: string;
    /**
     * Unique ID of the parameter.
     * @type {string}
     * @memberof BTMParameter1
     */
    parameterId?: string;
}

/**
 * Check if a given object implements the BTMParameter1 interface.
 */
export function instanceOfBTMParameter1(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BTMParameter1FromJSON(json: any): BTMParameter1 {
    return BTMParameter1FromJSONTyped(json, false);
}

export function BTMParameter1FromJSONTyped(json: any, ignoreDiscriminator: boolean): BTMParameter1 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    if (!ignoreDiscriminator) {
        if (json['btType'] === 'BTMDatabaseParameter-2229') {
            return BTMDatabaseParameter2229FromJSONTyped(json, true);
        }
        if (json['btType'] === 'BTMParameterAppearance-627') {
            return BTMParameterAppearance627FromJSONTyped(json, true);
        }
        if (json['btType'] === 'BTMParameterArray-2025') {
            return BTMParameterArray2025FromJSONTyped(json, true);
        }
        if (json['btType'] === 'BTMParameterBlobReference-1679') {
            return BTMParameterBlobReference1679FromJSONTyped(json, true);
        }
        if (json['btType'] === 'BTMParameterBoolean-144') {
            return BTMParameterBoolean144FromJSONTyped(json, true);
        }
        if (json['btType'] === 'BTMParameterConfigured-2222') {
            return BTMParameterConfigured2222FromJSONTyped(json, true);
        }
        if (json['btType'] === 'BTMParameterDerived-864') {
            return BTMParameterDerived864FromJSONTyped(json, true);
        }
        if (json['btType'] === 'BTMParameterEnum-145') {
            return BTMParameterEnum145FromJSONTyped(json, true);
        }
        if (json['btType'] === 'BTMParameterFeatureList-1749') {
            return BTMParameterFeatureList1749FromJSONTyped(json, true);
        }
        if (json['btType'] === 'BTMParameterForeignId-146') {
            return BTMParameterForeignId146FromJSONTyped(json, true);
        }
        if (json['btType'] === 'BTMParameterInvalid-1664') {
            return BTMParameterInvalid1664FromJSONTyped(json, true);
        }
        if (json['btType'] === 'BTMParameterLookupTablePath-1419') {
            return BTMParameterLookupTablePath1419FromJSONTyped(json, true);
        }
        if (json['btType'] === 'BTMParameterMaterial-1388') {
            return BTMParameterMaterial1388FromJSONTyped(json, true);
        }
        if (json['btType'] === 'BTMParameterMultiEnum-3411') {
            return BTMParameterMultiEnum3411FromJSONTyped(json, true);
        }
        if (json['btType'] === 'BTMParameterQuantity-147') {
            return BTMParameterQuantity147FromJSONTyped(json, true);
        }
        if (json['btType'] === 'BTMParameterQueryList-148') {
            return BTMParameterQueryList148FromJSONTyped(json, true);
        }
        if (json['btType'] === 'BTMParameterQueryWithOccurrenceList-67') {
            return BTMParameterQueryWithOccurrenceList67FromJSONTyped(json, true);
        }
        if (json['btType'] === 'BTMParameterReference-2434') {
            return BTMParameterReference2434FromJSONTyped(json, true);
        }
        if (json['btType'] === 'BTMParameterString-149') {
            return BTMParameterString149FromJSONTyped(json, true);
        }
        if (json['btType'] === 'BTMReadOnlyParameter-3800') {
            return BTMReadOnlyParameter3800FromJSONTyped(json, true);
        }
    }
    return {
        
        'btType': !exists(json, 'btType') ? undefined : json['btType'],
        'importMicroversion': !exists(json, 'importMicroversion') ? undefined : json['importMicroversion'],
        'nodeId': !exists(json, 'nodeId') ? undefined : json['nodeId'],
        'parameterId': !exists(json, 'parameterId') ? undefined : json['parameterId'],
    };
}

export function BTMParameter1ToJSON(value?: BTMParameter1 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'btType': value.btType,
        'importMicroversion': value.importMicroversion,
        'nodeId': value.nodeId,
        'parameterId': value.parameterId,
    };
}

