/* tslint:disable */
/* eslint-disable */
/**
 * Onshape REST API
 * ## Welcome to the Onshape REST API Explorer  To use this API explorer, sign in to your [Onshape](https://cad.onshape.com) account in another tab, then click the **Try it out** button below (it toggles to a **Cancel** button when selected).  See the **[API Explorer Guide](https://onshape-public.github.io/docs/api-intro/explorer/)** for help navigating this API Explorer, including **[authentication](https://onshape-public.github.io/docs/api-intro/explorer/#authentication)**.  **Tip:** To ensure the current session isn\'t used when trying other authentication techniques, make sure to [remove the Onshape cookie](https://support.google.com/chrome/answer/95647#zippy=%2Cdelete-cookies-from-a-site) as per the instructions for your browser. Alternatively, you can use a private or incognito window.  ## See Also  * [Onshape API Guide](https://onshape-public.github.io/docs/): Our full suite of developer guides, to be used as an accompaniment to this API Explorer. * [Onshape Developer Portal](https://dev-portal.onshape.com/): The Onshape portal for managing your API keys, OAuth2 credentials, your Onshape applications, and your Onshape App Store entries. * [Authentication Guide](https://onshape-public.github.io/docs/auth/): Our guide to using API keys, request signatures, and OAuth2 in  your Onshape applications.
 *
 * The version of the OpenAPI document: 1.181.37085-cf05a13421a3
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
     BTSketchArcDisplayData349FromJSONTyped,
     BTSketchCircleDisplayData350FromJSONTyped,
     BTSketchCompositeEntityDisplayData1093FromJSONTyped,
     BTSketchConicDisplayData1085FromJSONTyped,
     BTSketchEllipseDisplayData712FromJSONTyped,
     BTSketchEllipticalArcDisplayData892FromJSONTyped,
     BTSketchLineDisplayData357FromJSONTyped,
     BTSketchPointDisplayData358FromJSONTyped,
     BTSketchSplineDisplayData359FromJSONTyped
} from './';

/**
 * 
 * @export
 * @interface BTSketchEntityDisplayData354
 */
export interface BTSketchEntityDisplayData354 {
    /**
     * Type of JSON object.
     * @type {string}
     * @memberof BTSketchEntityDisplayData354
     */
    btType?: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof BTSketchEntityDisplayData354
     */
    points?: Array<number>;
}

/**
 * Check if a given object implements the BTSketchEntityDisplayData354 interface.
 */
export function instanceOfBTSketchEntityDisplayData354(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BTSketchEntityDisplayData354FromJSON(json: any): BTSketchEntityDisplayData354 {
    return BTSketchEntityDisplayData354FromJSONTyped(json, false);
}

export function BTSketchEntityDisplayData354FromJSONTyped(json: any, ignoreDiscriminator: boolean): BTSketchEntityDisplayData354 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    if (!ignoreDiscriminator) {
        if (json['btType'] === 'BTSketchArcDisplayData-349') {
            return BTSketchArcDisplayData349FromJSONTyped(json, true);
        }
        if (json['btType'] === 'BTSketchCircleDisplayData-350') {
            return BTSketchCircleDisplayData350FromJSONTyped(json, true);
        }
        if (json['btType'] === 'BTSketchCompositeEntityDisplayData-1093') {
            return BTSketchCompositeEntityDisplayData1093FromJSONTyped(json, true);
        }
        if (json['btType'] === 'BTSketchConicDisplayData-1085') {
            return BTSketchConicDisplayData1085FromJSONTyped(json, true);
        }
        if (json['btType'] === 'BTSketchEllipseDisplayData-712') {
            return BTSketchEllipseDisplayData712FromJSONTyped(json, true);
        }
        if (json['btType'] === 'BTSketchEllipticalArcDisplayData-892') {
            return BTSketchEllipticalArcDisplayData892FromJSONTyped(json, true);
        }
        if (json['btType'] === 'BTSketchLineDisplayData-357') {
            return BTSketchLineDisplayData357FromJSONTyped(json, true);
        }
        if (json['btType'] === 'BTSketchPointDisplayData-358') {
            return BTSketchPointDisplayData358FromJSONTyped(json, true);
        }
        if (json['btType'] === 'BTSketchSplineDisplayData-359') {
            return BTSketchSplineDisplayData359FromJSONTyped(json, true);
        }
    }
    return {
        
        'btType': !exists(json, 'btType') ? undefined : json['btType'],
        'points': !exists(json, 'points') ? undefined : json['points'],
    };
}

export function BTSketchEntityDisplayData354ToJSON(value?: BTSketchEntityDisplayData354 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'btType': value.btType,
        'points': value.points,
    };
}

